### PR TITLE
Use JsonPropertyName in JsonStringEnumMemberConverter.

### LINKED ISSUE #16: JsonStringEnumMemberConverter should use JsonPropertyName if present
This should work

```cs
[JsonConverter(typeof(JsonStringEnumMemberConverter))]
enum A
{
  [JsonPropertyName("abc")]
  X,
}
```

### PR DESCRIPTION
**Pull request by NN---**
Fixes #16.

### CODE REVIEW

**Comment by CodeBlanch** [comment]
Thanks @NN---! I'm going to merge and tweak it a bit. I'll reply back when a beta is up on nuget.

**Comment by NN---** [comment]
Sure. Btw I implemented only serialize  to json and didn’t implement deserializing.

**Comment by CodeBlanch** [comment]
2.1.0-beta1 should be up on nuget shortly. When you have time please take that for a spin and let me know if everything looks good for your use cases! Thanks again.

**Comment by NN---** [comment]
https://github.com/dotnet/runtime/issues/31619

**Comment by 0xced** [comment]
I just used this new feature for https://github.com/emmettnicholas/StacMan/pull/12 and everything works fine.

**Pull request merged**
